<?php
/**
 * @file
 * Makes WYSIWYG tables responsive, when filter is enabled for the field.
 */

/**
 * Implements hook_filter_info().
 */
function utexas_tablesaw_filter_filter_info() {
  $filters = array();
  $filters['tablesaw'] = array(
    'title' => t('Make WYSIWYG tables responsive'),
    'process callback' => '_tablesaw_filter',
  );
  return $filters;
}

/**
 * Filter callback for tablesaw filter.
 */
function _tablesaw_filter($text, $filter, $format, $langcode, $cache, $cache_id) {
  // Add tablesaw classes & data-mode to the <table> element.
  return preg_replace('/<table(.*)>/i', '<table class="tablesaw tablesaw-stack" data-tablesaw-mode="stack">', $text);
}

/**
 * Implements hook_preprocess_page().
 *
 * Adds tablesaw JS and CSS when tables present.
 */
function utexas_tablesaw_filter_preprocess_page(&$variables) {
  if (isset($variables['node'])) {
    $formats_with_tablesaw = array();
    // Get text formats that have "tablesaw filter" enabled.
    $result = db_query('SELECT n.format FROM {filter} n WHERE n.module = :module AND n.status = 1', array(':module' => 'utexas_tablesaw_filter'));
    foreach ($result as $record) {
      $formats_with_tablesaw[] = $record->format;
    }
    array_unique($formats_with_tablesaw);
    $node = $variables['node'];
    $field_info = field_info_instances('node', $node->type);
    $fields = array_keys($field_info);
    foreach ($fields as $field) {
      $f = $field;
      // Add the required JS and CSS only if the following three conditions:
      // (1) The field must have a text format value
      // (2) The field format must have tablesaw filter enabled
      // (3) The field value must contain '<table'.
      if (isset($node->{$f}['und'][0]['format']) && in_array($node->{$f}['und'][0]['format'], $formats_with_tablesaw) && preg_match('/<table/', $node->{$f}['und'][0]['value'])) {
        if (file_exists(path_to_theme() . '/js/tablesaw.js')) {
          drupal_add_js(path_to_theme() . '/js/tablesaw.js', array('scope' => 'foot_scripts', 'weight' => 30));
          // The CSS included in this module is not needed, as it is already
          // provided by the theme (_tablesaw.scss).
        }
        elseif (file_exists(libraries_get_path('tablesaw') . '/dist/tablesaw.js')) {
          drupal_add_js(libraries_get_path('tablesaw') . '/dist/tablesaw.js', array('scope' => 'foot_scripts', 'weight' => 30));
        }
        else {
          drupal_set_message('The tablesaw filter is enabled, but its library could not be found.', 'warning');
        }
        // Quit the loop as soon as a single field that needs tablesaw is found.
        break;
      }
    }
  }
}
