<?php

/**
 * UTLogin user credentials for simpletest tests.
 *
 * Data structure is expected to be in the following format (note that the
 * 'cookies' value should be an empty array):
 * @code
 * array(
 *   'username1' => array(
 *     'name' => 'username1',
 *     'password' => '...',
 *     'cookies' => array(),
 *   ),
 *   'username2' => array(
 *     'name' => 'username2',
 *     'password' => '...',
 *     'cookies' => array(),
 *   ),
 * )
 * @endcode
 *
 * @see https://utdirect.utexas.edu/utdirect/apps/portaltest.WBX
 */
$conf['utlogin_simpletest_utlogin_users'] = array(
);
